/**
 * Unit tests for the configurable module definition.
 *
 * Layer: unit.
 * Goal: prove the ConfigurableModuleBuilder output bridges MODULE_OPTIONS_TOKEN
 * to the BYMAX_CONFIG_OPTIONS Symbol and exposes a class to extend, so the
 * options provider and the config provider share one injection token.
 * Mocks: none.
 */

import { ConfigurableModuleClass, MODULE_OPTIONS_TOKEN } from './config.module-definition'
import { BYMAX_CONFIG_OPTIONS } from './config.tokens'

describe('config module definition', () => {
  it('bridges MODULE_OPTIONS_TOKEN to the BYMAX_CONFIG_OPTIONS symbol', () => {
    /**
     * Token bridging.
     *
     * The builder is constructed with an explicit optionsInjectionToken so the
     * generated options provider registers under the package Symbol. The config
     * factory then injects that same Symbol; if the two drifted, resolution
     * would fail at bootstrap.
     */
    expect(MODULE_OPTIONS_TOKEN).toBe(BYMAX_CONFIG_OPTIONS)
  })

  it('exposes a class the module can extend', () => {
    /**
     * Extendable base class.
     *
     * BymaxConfigModule inherits forRoot / forRootAsync by extending this class,
     * so it must be a constructable function generated by the builder.
     */
    expect(typeof ConfigurableModuleClass).toBe('function')
  })
})
